config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  # 第三方引擎的路由
  use_doorkeeper

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register' }

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => '/cable'

  # 自定义路由
  resources :probe_settings, only: [:index, :create, :destroy] do
    collection do
      get :opml
    end
  end

  resources :web_spider_settings, only: [:create, :destroy]

  resources :rss_feeds, only: [:index] do
    collection do
      get :briefly_info
      get :unread_count
      put :mark_all_as_read
      get :load_more_rss_feed
      put :toggle_thumbs_up
      get :recommend
      get :favor
      get :recommend_feeds_of_specify_feed
      get :daily
    end
  end

  scope module: 'goods' do
    resources :goods, only: [] do
      collection do
        get 'comments'
        get 'prices'
        get 'coupons'
        get 'ads'
        get 'names'
      end
    end
  end

  # scope module: 'jobs_management' do
  #   resources :jobs_management, only: [] do
  #     collection do
  #       get 'running_jobs_count', as: 'running_jobs_count'
  #       post 'start_job', as: 'start_job'
  #       post 'start_all_jobs', as: 'start_all_jobs'
  #       delete 'delete_job', as: 'delete_job'
  #     end
  #   end
  # end

  get 'running_jobs_count' => 'jobs_management/jobs_management#running_jobs_count', as: 'running_jobs_count'
  post 'start_job' => 'jobs_management/jobs_management#start_job', as: 'start_job'
  post 'start_all_jobs' => 'jobs_management/jobs_management#start_all_jobs', as: 'start_all_jobs'
  delete 'delete_job' => 'jobs_management/jobs_management#delete_job', as: 'delete_job'
  get 'histories' => 'histories/histories#histories', as: 'histories'

  post 'sql' => 'sql#sql', as: 'sql'

  # constraints subdomain: "api" do
  #   namespace :api, path: nil do
      # namespace :v1 do
      #   match "*path", to: "api#gone", via: :all
      # end
    # end
  # end
end

app/models/concerns/rss_list.rb
module RSSList
  extend ActiveSupport::Concern

  included do |base|
  end

  module ClassMethods
    def rss_list(user_id, page = 1, per = 100)
      page ||= 1
      per ||= 100

      # FIXME: 修改用 AR 来实现
      ProbeSetting.find_by_sql(<<-SQL
      select ps.id as id,
        count(case when unread = true and urfs.user_id = #{user_id}
          then 1
          else NULL
        end) as unread_count
      from probe_settings as ps
      inner join user_rss_ships as urs
      on urs.user_id = #{user_id} and urs.probe_setting_id = ps.id
      left join rss_feeds as rf
        on rf.probe_setting_id = ps.id
      left join user_rss_feed_ships as urfs
        on urfs.rss_feed_id = rf.id
      left join rss_infos as ri
        on ri.probe_setting_id = ps.id
      group by ps.id
      limit #{per}
      offset #{ (page - 1) * per }
      SQL
      )
    end
  end
end

app/controllers/concerns/rss_list.rb
module RSSList
  extend ActiveSupport::Concern

  included do |base|
  end

  def rss_list(user_id = current_user.id, page = 1, per = 100)
    ProbeSetting.find_by_sql(<<-SQL
      select ps.id as id, 
        count(case when unread = true and urfs.user_id = #{user_id} 
          then 1 
          else NULL 
        end) as unread_count
      from probe_settings as ps
      inner join user_rss_ships as urs
      on urs.user_id = #{current_user.id} and urs.probe_setting_id = ps.id
      left join rss_feeds as rf
        on rf.probe_setting_id = ps.id
      left join user_rss_feed_ships as urfs
        on urfs.rss_feed_id = rf.id
      left join rss_infos as ri
        on ri.probe_setting_id = ps.id
      group by ps.id
      limit #{per}
      offset #{ (page - 1) * per }
    SQL
    )
  end

  module ClassMethods
  end
end

app/views/rss/rss/rss_list/_all_rss_list.vue.js.erb
// 定时轮询正在运行的后台任务数量
setInterval(function () {
    axios.get('<%= running_jobs_count_path %>', {
        headers: {
            'Accept': 'application/json'
        }
    })
        .then(function (reason) {
            app._data.rss_running_missions = reason.data.running_rss_jobs_count
            // app._data.good_running_missions = reason.data.running_goods_jobs_count
        })
        .catch(function (reason) {
        })
}, 5000)

<%= render 'history/refresh_history_dialog.vue.js' %>

Vue.component('all-rss-list', {
    props: [],
    data: function () {
        return {
            all_rss_list: <%= raw @all_rss_list_json.to_json %>,
            refresh_history_dialog_visible: false,
            setting_id: null,
            type: null
        }
    },
    methods: {
        select_tag_color: function (content) {
            var tag_color = null;
            switch (content) {
                case 'success':
                    tag_color = 'green';
                    break;
                case 'fail':
                    tag_color = 'red';
                    break;
                case 'performing':
                    tag_color = 'yellow';
                    break;
                case 'enqueued':
                    tag_color = '';
                    break;
                case 'enqueue':
                    tag_color = 'gray'
                    break;
                default:
                    break;
            }
            return tag_color;
        },
        start_job: function (type, id) {
            var that = this

            axios.post('<%= start_job_path %>', {
                    type: type,
                    id: id,
                    authenticity_token: document.getElementsByName("csrf-token")[0].getAttribute('content'),
                },
                {
                    headers: {
                        'Accept': 'application/json'
                    }
                })
                .then(function (reason) {
                    that.$message.success(reason.data.message)
                })
                .catch(function (reason) {
                    that.$message.error(reason.toString())
                })
        },
        delete_job: function (jid) {
            var that = this

            axios.delete('<%= delete_job_path %>', {
                headers: {
                    'Accept': 'application/json'
                },
                params: {
                    jid: jid,
                    authenticity_token: document.getElementsByName("csrf-token")[0].getAttribute('content'),
                }
            })
                .then(function (reason) {
                    that.$message.success(reason.data.message)
                })
                .catch(function (reason) {
                    that.$message.error(reason.toString())
                })
        },
        show_history_dialog: function (setting_id) {
            this.refresh_history_dialog_visible = true
            this.setting_id = setting_id
            this.type = 0
        },
        edit_setting: function (setting_id) {

        },
        delete_setting: function (setting_id) {
        var that = this;

        this.$confirm({
                title: 'Confirm',
                content: 'Do you want to delete this item?',
                onOk() {
                    axios.delete('/probe_settings/' + setting_id, {
                        headers: {
                            'Accept': 'application/json'
                        },
                        params: {
                            authenticity_token: document.getElementsByName("csrf-token")[0].getAttribute('content'),
                        }
                    })
                        .then(function (reason) {
                            that.$message.success(reason.data.message)
                        })
                        .catch(function (reason) {
                            that.$message.error(reason.toString())
                        })
                },
                onCancel() {},
            });
        }
    },
    template: '<%= import_partial('rss/rss/rss_list/all_rss_list_templ') %>'
})